name: 🐛 오류 제보
about: 정상적으로 작동하지 않는 기능 제보
labels: ["bug"]

body:
  - type: textarea
    attributes:
      label: 오류 설명
      description: 어떤 오류가 발생하는지 명확하게 설명해주세요.
      placeholder: 요금제 찾기에 들어간 뒤, 새로고침을 하면 [오류가 발생했습니다] 문구가 표시돼요.
    validations:
      required: true

  - type: textarea
    attributes:
      label: 정상 상황
      description: 정상적인 경우에는 어떻게 작동해야 하는지 설명해주세요.
      placeholder: 방금 전 본 페이지와 같은 내용이 표시되어야 해요.
    validations:
      required: true

  - type: textarea
    attributes:
      label: 재현 방법
      description: 해당 오류를 재현하기 위한 자세한 방법을 순서대로 적어주세요.
      value: |
        1. '...' 로 이동한다.
        2. '...' 버튼을 누른다.
        3. 에러 현상이 발생한다.
      render: markdown
    validations:
      required: true

  - type: textarea
    attributes:
      label: 추가 컨텍스트
      description: |
        문제 상황을 더 잘 설명할 수 있는 스크린샷, 로그, 기존 이슈 등을 첨부해주세요.
        Tip: 이 영역에 이미지 또는 로그 파일을 드래그해 첨부할 수 있어요.
    validations:
      required: false
